export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DIRECTOR: 'DIRECTOR',
  ACADEMIC_COORDINATOR: 'ACADEMIC_COORDINATOR',
  CLASS_TEACHER: 'CLASS_TEACHER',
  SUBJECT_TEACHER: 'SUBJECT_TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  TRANSPORT_MANAGER: 'TRANSPORT_MANAGER',
  HOBBY_COORDINATOR: 'HOBBY_COORDINATOR',
  IT_ADMIN: 'IT_ADMIN',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const ADMIN_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.DIRECTOR,
  Role.IT_ADMIN,
];

export const TEACHER_ROLES: Role[] = [
  Role.ACADEMIC_COORDINATOR,
  Role.CLASS_TEACHER,
  Role.SUBJECT_TEACHER,
];

export const STAFF_ROLES: Role[] = [
  Role.ACCOUNTANT,
  Role.TRANSPORT_MANAGER,
  Role.HOBBY_COORDINATOR,
];
