import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { LogIncidentDto } from './dto/log-incident.dto';
import { CreateActionDto } from './dto/create-action.dto';

const MINOR_INCIDENT_RED_FLAG_THRESHOLD = 3;

@Injectable()
export class DisciplineService {
  constructor(private prisma: PrismaService) {}

  async logIncident(dto: LogIncidentDto, reportedBy: string) {
    const student = await this.prisma.student.findUnique({ where: { id: dto.studentId } });
    if (!student) throw new NotFoundException('Student not found');

    const incident = await this.prisma.incident.create({
      data: {
        studentId: dto.studentId,
        reportedBy,
        date: new Date(dto.date),
        time: dto.time,
        type: dto.type,
        severity: dto.severity,
        description: dto.description,
        witnesses: dto.witnesses ?? [],
        location: dto.location,
      },
      include: {
        student: {
          include: { user: { select: { firstName: true, lastName: true } } },
        },
        reporter: { select: { firstName: true, lastName: true } },
      },
    });

    // Auto-generate red flag if 3+ minor incidents
    if (dto.severity === 'MINOR') {
      await this.checkAndCreateRedFlag(dto.studentId);
    }

    // Auto-escalate serious incidents
    if (dto.severity === 'SERIOUS') {
      await this.prisma.incident.update({
        where: { id: incident.id },
        data: { status: 'UNDER_REVIEW' },
      });
    }

    return incident;
  }

  private async checkAndCreateRedFlag(studentId: string) {
    const minorIncidents = await this.prisma.incident.findMany({
      where: {
        studentId,
        severity: 'MINOR',
        status: { notIn: ['RESOLVED'] },
      },
      select: { id: true },
    });

    if (minorIncidents.length >= MINOR_INCIDENT_RED_FLAG_THRESHOLD) {
      // Check if there's already an active red flag
      const existingRedFlag = await this.prisma.redFlag.findFirst({
        where: { studentId, status: 'ACTIVE', autoGenerated: true },
      });

      if (!existingRedFlag) {
        await this.prisma.redFlag.create({
          data: {
            studentId,
            reason: `Student has accumulated ${minorIncidents.length} minor incidents`,
            autoGenerated: true,
            incidentIds: minorIncidents.map((i) => i.id),
          },
        });
      } else {
        // Update the existing red flag with the new incident IDs
        await this.prisma.redFlag.update({
          where: { id: existingRedFlag.id },
          data: { incidentIds: minorIncidents.map((i) => i.id) },
        });
      }
    }
  }

  async getIncidents(filters: {
    studentId?: string;
    classId?: string;
    status?: string;
    severity?: string;
    type?: string;
  }) {
    const whereClause: Record<string, unknown> = {};

    if (filters.studentId) {
      whereClause.studentId = filters.studentId;
    }
    if (filters.status) {
      whereClause.status = filters.status;
    }
    if (filters.severity) {
      whereClause.severity = filters.severity;
    }
    if (filters.type) {
      whereClause.type = filters.type;
    }
    if (filters.classId) {
      whereClause.student = { classId: filters.classId };
    }

    return this.prisma.incident.findMany({
      where: whereClause,
      include: {
        student: {
          include: {
            user: { select: { firstName: true, lastName: true } },
            class: { select: { name: true } },
            section: { select: { name: true } },
          },
        },
        reporter: { select: { firstName: true, lastName: true } },
        disciplinaryActions: {
          select: { id: true, actionType: true, status: true },
        },
      },
      orderBy: { date: 'desc' },
    });
  }

  async getIncidentById(id: string) {
    const incident = await this.prisma.incident.findUnique({
      where: { id },
      include: {
        student: {
          include: {
            user: { select: { firstName: true, lastName: true } },
            class: { select: { name: true } },
            section: { select: { name: true } },
          },
        },
        reporter: { select: { firstName: true, lastName: true } },
        disciplinaryActions: {
          include: {
            assigner: { select: { firstName: true, lastName: true } },
          },
        },
      },
    });
    if (!incident) throw new NotFoundException('Incident not found');
    return incident;
  }

  async updateIncidentStatus(id: string, status: string) {
    const incident = await this.prisma.incident.findUnique({ where: { id } });
    if (!incident) throw new NotFoundException('Incident not found');

    return this.prisma.incident.update({
      where: { id },
      data: { status },
    });
  }

  async createAction(dto: CreateActionDto, assignedBy: string) {
    const incident = await this.prisma.incident.findUnique({ where: { id: dto.incidentId } });
    if (!incident) throw new NotFoundException('Incident not found');

    const action = await this.prisma.disciplinaryAction.create({
      data: {
        incidentId: dto.incidentId,
        actionType: dto.actionType,
        assignedBy,
        description: dto.description,
        startDate: dto.startDate ? new Date(dto.startDate) : undefined,
        endDate: dto.endDate ? new Date(dto.endDate) : undefined,
        parentNotified: dto.parentNotified ?? false,
      },
      include: {
        incident: {
          include: {
            student: {
              include: { user: { select: { firstName: true, lastName: true } } },
            },
          },
        },
        assigner: { select: { firstName: true, lastName: true } },
      },
    });

    // Update incident status
    await this.prisma.incident.update({
      where: { id: dto.incidentId },
      data: { status: 'UNDER_REVIEW' },
    });

    return action;
  }

  async getRedFlags(filters: { studentId?: string; status?: string }) {
    return this.prisma.redFlag.findMany({
      where: {
        ...(filters.studentId && { studentId: filters.studentId }),
        ...(filters.status && { status: filters.status }),
      },
      include: {
        student: {
          include: {
            user: { select: { firstName: true, lastName: true } },
            class: { select: { name: true } },
            section: { select: { name: true } },
          },
        },
      },
      orderBy: { triggeredAt: 'desc' },
    });
  }

  async resolveRedFlag(id: string, resolvedBy: string) {
    const redFlag = await this.prisma.redFlag.findUnique({ where: { id } });
    if (!redFlag) throw new NotFoundException('Red flag not found');

    return this.prisma.redFlag.update({
      where: { id },
      data: { status: 'RESOLVED', resolvedAt: new Date(), resolvedBy },
    });
  }
}
