const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();
async function main() {
  console.log('=== Phase 1 ===');
  console.log('Users:', await p.user.count());
  console.log('Students:', await p.student.count());
  console.log('Classes:', await p.class.count());
  console.log('Sections:', await p.section.count());
  console.log('Subjects:', await p.subject.count());
  console.log('Enquiries:', await p.admissionEnquiry.count());
  console.log('Attendance:', await p.attendance.count());
  console.log('Syllabi:', await p.syllabus.count());
  console.log('Chapters:', await p.chapter.count());
  console.log('Timetables:', await p.timetable.count());
  console.log('TimetableSlots:', await p.timetableSlot.count());
  console.log('');
  console.log('=== Phase 2 ===');
  console.log('LMS Content:', await p.lmsContent.count());
  console.log('Question Banks:', await p.questionBank.count());
  console.log('Questions:', await p.question.count());
  console.log('Assessments:', await p.assessment.count());
  console.log('Grades:', await p.grade.count());
  console.log('');
  console.log('=== Phase 3 ===');
  console.log('Fee Heads:', await p.feeHead.count());
  console.log('Payments:', await p.payment.count());
  console.log('DefaulterRecords:', await p.defaulterRecord.count());
  console.log('Incidents:', await p.incident.count());
  console.log('Red Flags:', await p.redFlag.count());
  console.log('Vehicles:', await p.vehicle.count());
  console.log('Routes:', await p.route.count());
  console.log('');
  console.log('=== Phase 4 ===');
  console.log('Hobbies:', await p.hobby.count());
  console.log('Hobby Enrollments:', await p.hobbyEnrollment.count());
  console.log('PTM Slots:', await p.pTMSlot.count());
  console.log('Notifications:', await p.notification.count());
}
main().finally(() => p.$disconnect());
